### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by heixiaoma** [SimonAlong/Neo#10]
Exception in thread "main" java.lang.NoClassDefFoundError: org/hibernate/service/jdbc/connections/spi/MultiTenantConnectionProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at top.hserver.core.ioc.util.ClassLoadUtil.LoadClasses(ClassLoadUtil.java:60)
	at top.hserver.core.ioc.ref.ClasspathPackageScanner.getConfigurationPackage(ClasspathPackageScanner.java:53)
	at top.hserver.core.ioc.ref.InitBean.initConfiguration(InitBean.java:52)
	at top.hserver.core.ioc.ref.InitBean.init(InitBean.java:39)
	at top.hserver.HServerApplication.run(HServerApplication.java:25)
	at com.mysql.Main.main(Main.java:7)
Caused by: java.lang.ClassNotFoundException: org.hibernate.service.jdbc.connections.spi.MultiTenantConnectionProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by heixiaoma** [comment]
是我自己的程序问题，扫包，搞错了

**Comment by SimonAlong** [comment]
好的
